### ISSUE TITLE
Unexpected keyword argument 'json'

### ISSUE THREAD

**Issue by JustKiddingCode** [h44z/gitlab_to_gitea#1]
Hi,

maybe I need a little bit more steps. 
I tried your script with python 3.7.4
and installed pygitea and python-gitlab via pip.
I configured the user source with ldap in gitea and tried
to import everything else with the script.
I get this bug:

```
No public keys for user feng, importing!
Traceback (most recent call last):
  File "./migrate.py", line 619, in <module>
    main()
  File "./migrate.py", line 56, in main
    import_users_groups(gl, gt)
  File "./migrate.py", line 535, in import_users_groups
    _import_users(gitea_api, users, notify)
  File "./migrate.py", line 462, in _import_users
    _import_user_keys(gitea_api, keys, user)
  File "./migrate.py", line 471, in _import_user_keys
    "title": key.title,
TypeError: post() got an unexpected keyword argument 'json'
```

**Comment by h44z** [comment]
@JustKiddingCode did you install my custom version of pygitea? 
Install it from here: https://github.com/h44z/pygitea

**Comment by JustKiddingCode** [comment]
Thanks, that did the trick.
Some suggestion, you could use getpass so i don't have to store the gitlab admin password.

Thanks again!
