### ISSUE TITLE
error docker execution

### ISSUE THREAD

**Issue by ilsaul** [h44z/gitlab_to_gitea#11]
Hi,
i try to migrate some all my project from gitlab to gitea because gitlab problem on write new repo. After create all group/society i receive this error.

sync_1  | The above exception was the direct cause of the following exception:
sync_1  | 
sync_1  | Traceback (most recent call last):
sync_1  |   File "migrate.py", line 650, in <module>
sync_1  |     main()
sync_1  |   File "migrate.py", line 55, in main
sync_1  |     import_projects(gl, gt)
sync_1  |   File "migrate.py", line 556, in import_projects
sync_1  |     projects: gitlab.v4.objects.Project = gitlab_api.projects.list(all=True)
sync_1  |   File "/usr/local/lib/python3.6/site-packages/gitlab/exceptions.py", line 306, in wrapped_f
sync_1  |     raise error(e.error_message, e.response_code, e.response_body) from e
sync_1  | gitlab.exceptions.GitlabListError: 500: 500 Internal Server Error
gitlab_to_gitea_sync_1 exited with code 1

any sugest?

thank you

**Comment by h44z** [comment]
I currently don't have a testing instance to reproduce the problem, maybe someone else can provide more information about the gitlab 500 error?
