### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by theerror** [h44z/gitlab_to_gitea#3]
Hi, I'm not familiar with python, so I can't figure it out. Could you help, what I can miss? Installation of requirements passed fine, but running the script isn't. 

```text
# python3 -V
Python 3.5.3

# python3 migrate.py
  File "migrate.py", line 69
    label_response: requests.Response = gitea_api.get("/repos/" + owner + "/" + repo + "/labels")
                  ^
SyntaxError: invalid syntax
```

**Comment by h44z** [comment]
Can you please retry with python version >= 3.7 ?

**Comment by theerror** [comment]
ahh, that makes the trick...  I had little obstruction with, but Python 3.7.6 were working... Thank you!

Could be fine, to note i in README.
