### ISSUE TITLE
get_user_or_group only works with users

### ISSUE THREAD

**Issue by user-name-is-taken** [h44z/gitlab_to_gitea#4]
The function [get_user_or_group](https://github.com/h44z/gitlab_to_gitea/blob/15dec56422ea61e43349ba1749e67840bd695ac9/migrate.py#L136) only works with users, not with groups. Adding an [org option](https://try.gitea.io/api/swagger) might fix it

**Comment by h44z** [comment]
pull requests welcome ;)
